import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { RQProvider, MSWProvider } from '@/providers';
import { SpeedInsights } from '@vercel/speed-insights/next';

import './globals.css';

if (
  process.env.NODE_ENV === 'development' &&
  process.env.NEXT_PUBLIC_MODE === 'mock' &&
  process.env.NEXT_RUNTIME === 'nodejs'
) {
  const { server } = await import('@/mocks/server');
  server.listen();
}

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          antialiased
        `}
      >
        <MSWProvider>
          <RQProvider>{children}</RQProvider>
        </MSWProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
